### PR TITLE
adding quagga_router type and provider

### PR DESCRIPTION
**Pull request by m4ce**
This one is to support basic commands like 'hostname' etc. I couldn't really come up with a better type/provider name!

Take a look and let me know if anything looks weird.

### CODE REVIEW

**Comment by bibigon812** [comment]
Maybe it could be called quagga_general, but it's not clear too.

**Comment by bibigon812** [comment]
Or quagga_global.

**Comment by m4ce** [comment]
I guess either quagga_global or quagga_system? As in like system settings (e.g. hostname).

You pick!

**Comment by bibigon812** [comment]
I think quagga_system is a good choice.

**Pull request merged**
