### PR TITLE
Quagga IP type and provider

### PR DESCRIPTION
**Pull request by m4ce**
Since I had to support ip forwarding, I just renamed the pim type and provider that you previously merged to quagga_ip, as discussed in the other PR.

I only added IP multicast routing and forwarding as that is all I need for now.

### CODE REVIEW

**Comment by m4ce** [comment]
I think I should be done with the PRs for today :)

I reckon there might be area of improvements in the Puppet manifests. For instance, driving the module data via Hiera. Perhaps we can chat about that a bit later.

**Comment by bibigon812** [comment]
Thank you! It's a great.

**Comment by bibigon812** [comment]
What if we'll put together `pim_interface` and `ospf_interface` and create `quagga_interface`?

**Comment by m4ce** [comment]
I guess quagga_interface can also manage zebra interface stuff. I think it's a good idea!

**Pull request merged**
