### PR TITLE
Adding pim type and provider

### PR DESCRIPTION
**Pull request by m4ce**
Allows to manage for now simple things like 'ip multicast-routing'.

### CODE REVIEW

**Comment by bibigon812** [comment]
Hi. Will you add tests?

**Comment by m4ce** [comment]
Ok squashed the commits and added the tests :)

**Comment by m4ce** [comment]
Actually, before merging, let me fix the ensurable stuff. It is not really needed here!

**Comment by m4ce** [comment]
Okay - ready for merge on my side.

**Comment by bibigon812** [comment]
Hi. What are you think about this:
```
ip { 'quagga':
  enshure => present,
  multicast => true,
  forwarding => true,
  ssmpingd => true|1.1.1.1,
}

ip_route { '10.0.0.0/8':
  ensure => present,
  next_hop => 1.1.1.1|eth0|blackhole|null|reject,
}
```

**Comment by m4ce** [comment]
That is quite nice!

Though, I reckon the only problem with something like `ip` and `ip_route` is the fact that they are so generic that they could easily clash with some type and providers coming from other puppet modules :/

I guess it'd be better to prefix all the types with quagga_? That's generally my approach why I write puppet type and providers..

**Comment by bibigon812** [comment]
Ok. You are right. I'll rename the types in a future major release `2.x.x`.

**Comment by m4ce** [comment]
Ok very cool. I actually have a few more things to commit but I will wait for you to cut out a 2.x release. If you create a branch, I can start pushing my stuff there alternatively!

**Comment by bibigon812** [comment]
I created the branch `1.2.x` of the current release. Can you push to `master`?

**Pull request merged**
